config:
  APIKey: XXX
  APISecret: XXX
  APIEndpoint: https://api.exchange.trade.io
  MinBTC: 0
  MaxBTC: 0
  MinETH: 0.01
  MaxETH: 0.1
  MinUSDT: 0
  MaxUSDT: 0
  MinProfit: 1.0031
  OrderMinuteLimit: 600
  OrderHourlyLimit : 3600
  OrderDailyLimit : 86000
  APIMinuteLimit: 1200
  APIHourlyLimit : 60000
  APIDailyLimit : 1400000
  Timezone: xxx
  Simulation: true
  Fees: 0.1
  LogLevel: INFO
  Exclusions:
    - ktos
    - btnt
    - coy
    - btc
    - ttv
    - dog
    - kick
    - xfrc
    - usdt
    - xrr
    - ttv