config:
  APIKey: XXX
  APISecret: XXX
  APIEndpoint: https://api.exchange.trade.io
  MinBTC: 0.001
  MaxBTC: 0.00154468
  MinETH: 0.01
  MaxETH: 0.08501381
  MinUSDT: 10
  MaxUSDT: 15.33288104
  MinProfit: 1.003
  OrderMinuteLimit: 600
  OrderHourlyLimit : 3600
  OrderDailyLimit : 86000
  APIMinuteLimit: 920
  APIHourlyLimit : 60000
  APIDailyLimit : 1400000
  Timeout: 0
  Simulation: true
  Fees: 1.001
  LogLevel: INFO
  StartDate: "2019-08-21 14:10:00"
  Exclusions:
    - ktos
    - btnt
    - ttv
    - dog
    - kick
    - xfrc
    - usdt
    - xrr
    - ttv
    - lamb
    - lto
    - edr
    - pco
    - hot
    - mco
    - ode
    - nexo
    - mana
    - xsg
    - tusd
    - sidt
    - aoa
    - solve
    - wpp
    - loom
    - bch
    - coy
    - link
    - zil