config:
  APIKey: XXX
  APISecret: XXX
  APIEndpoint: https://api.exchange.trade.io
  MinBTC: 0.001
  MaxBTC: 0.00115410
  MinETH: 0.01
  MaxETH: 0.09691111
  MinUSDT: 10
  MaxUSDT: 13.48573316
  MinProfit: 1.003
  OrderMinuteLimit: 600
  OrderHourlyLimit : 3600
  OrderDailyLimit : 86000
  APIMinuteLimit: 1200
  APIHourlyLimit : 60000
  APIDailyLimit : 1400000
  Timeout: 1000
  Simulation: true
  Fees: 0.001
  LogLevel: INFO
  Exclusions:
    - ktos
    - btnt
    - ttv
    - dog
    - kick
    - xfrc
    - usdt
    - xrr
    - ttv
    - lamb
    - lto
    - edr
    - pco
    - hot
    - mco
    - ode
    - nexo
    - mana
    - xsg
    - tusd
    - sidt
    - aoa
    - solve