config:
  APIKey: XXX
  APISecret: XXX
  APIEndpoint: https://api.exchange.trade.io
  MinBTC: 0.001
  MaxBTC: 0.01
  MinETH: 0.01
  MaxETH: 0.1
  MinUSDT: 10
  MaxUSDT: 11
  MinProfit: 1.003
  OrderMinuteLimit: 600
  OrderHourlyLimit : 3600
  OrderDailyLimit : 86000
  APIMinuteLimit: 1200
  APIHourlyLimit : 60000
  APIDailyLimit : 1400000
  Timeout: 800
  Simulation: true
  Fees: 0.1
  LogLevel: INFO
  Exclusions:
    - ktos
    - btnt
    - coy
    - btc
    - ttv
    - dog
    - kick
    - xfrc
    - usdt
    - xrr
    - ttv