config:
  APIKey: 8bbcf739-e5f9-46df-8a07-884aeaa9e7d1
  APISecret: 100ad32f-5e7b-4a37-8c7f-e1199d1943db
  APIEndpoint: https://api.exchange.trade.io
  MinBTC: 0.001
  MaxBTC: 0.00179364
  MinETH: 0.01
  MaxETH: 0.07138272
  MinUSDT: 10
  MaxUSDT: 16.58796036
  MinProfit: 1.003
  OrderMinuteLimit: 600
  OrderHourlyLimit : 3600
  OrderDailyLimit : 86000
  APIMinuteLimit: 970
  APIHourlyLimit : 60000
  APIDailyLimit : 1400000
  Timeout: 0
  Fees: 1.001
  StartSecond: 0
  EndSecond: 5
  Debug: false
  Exclusions:
    - ktos
    - btnt
    - ttv
    - dog
    - kick
    - xfrc
    - usdt
    - xrr
    - ttv
    - lamb
    - lto
    - edr
    - pco
    - hot
    - mco
    - ode
    - nexo
    - mana
    - xsg
    - tusd
    - sidt
    - aoa
    - solve
    - wpp
    - loom
    - bch
    - coy
    - link
    - zil